import Head from "next/head";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [mobileNumber, setMobileNumber] = useState("");
  const [isOtpInputVisible, setOtpInputVisible] = useState(false);

  const onMobileChange = (e) => {
    const phoneInp = e.target.value;
    if (phoneInp.length <= 10) {
      setMobileNumber(phoneInp);
      if (!isOtpInputVisible && phoneInp.length === 10) {
        showOtpInput();
      }
    }
  };

  const hideOtpInput = () => {
    setOtpInputVisible(false);
  };

  const showOtpInput = () => {
    setOtpInputVisible(true);
  };

  const reset = () => {
    setMobileNumber("");
    hideOtpInput();
  };

  useEffect(() => {
    if ("OTPCredential" in window) {
      const ac = new AbortController();
      const input = document.querySelector(
        'input[autocomplete="one-time-code"]'
      );
      if (!input) return;

      navigator.credentials
        .get({ otp: { transport: ["sms"] }, signal: ac.signal })
        .then((otp) => {
          input.value = otp.code;
          alert(`OTP: ${otp.code}`);
        })
        .catch((err) => console.log("OTP Error:", err));
    }
  }, [isOtpInputVisible]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Your Bug Finder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <form className={styles.formCon}>
          <button onClick={reset}>reset</button>
          <input
            type="text"
            value={mobileNumber}
            onChange={onMobileChange}
            placeholder="Enter mobile number"
          />
          {isOtpInputVisible && (
            <>
              <p>Enter OTP:</p>
              <input
                type="text"
                inputMode="numeric"
                autoComplete="one-time-code"
              />
            </>
          )}
        </form>
      </main>
    </div>
  );
}
