import Head from "next/head";
import { useEffect } from "react";
import styles from "../styles/Home.module.css";

export default function Home() {
  useEffect(() => {
    if ("OTPCredential" in window) {
      const ac = new AbortController();
      const input = document.querySelector(
        'input[autocomplete="one-time-code"]'
      );
      if (!input) return;

      navigator.credentials
        .get({ otp: { transport: ["sms"] }, signal: ac.signal })
        .then((otp) => {
          input.value = otp.code;
          alert(`OTP: ${otp.code}`);
        })
        .catch((err) => console.log("OTP Error:", err));
    }
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <p>Enter OTP:</p>
          <input type="text" inputMode="numeric" autoComplete="one-time-code" />
        </div>
      </main>
    </div>
  );
}
